// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoNPonA-JZrVMRtzfKvnm4K7NaVjNFgI8',
    appId: '1:539425728536:web:763f8471feeb43ceb2fb6d',
    messagingSenderId: '539425728536',
    projectId: 'zaman-6d048',
    authDomain: 'zaman-6d048.firebaseapp.com',
    storageBucket: 'zaman-6d048.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOiE3afEvk_ekepvahefGouukZ74hco8M',
    appId: '1:539425728536:android:7d8e2c17ef24e370b2fb6d',
    messagingSenderId: '539425728536',
    projectId: 'zaman-6d048',
    storageBucket: 'zaman-6d048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZZhYlGI_5iAKMLW5bOvX8RpX6Nl_bgM',
    appId: '1:539425728536:ios:4f73892ccc6f8d36b2fb6d',
    messagingSenderId: '539425728536',
    projectId: 'zaman-6d048',
    storageBucket: 'zaman-6d048.firebasestorage.app',
    iosBundleId: 'com.example.zaman',
  );
}
